language: julia
sudo: required
dist: trusty
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
after_success:
  - julia -e 'cd(Pkg.dir("AutoScenes")); Pkg.add("AutoScenes"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
